namespace OES.Helper.Enums
{
    public enum CustomCodeStatus
    {
        // WARNING: Don't change the indexes values of the enum members, to maintain integrity with the clients' CustomCodeStatus enums.
        Success = 0,

        // WARNING: Don't change the indexes values of the enum members, to maintain integrity with the clients' CustomCodeStatus enums.
        SomethingWentWrong,
        UserNotFound,
        SampleClassFaildToAdded,
        ThisOrganizationModelNotValid,
        NotFound,
        ParentOrganizationNotFound,
        Forbidden,
        ItemBankParentNotValid,
        ItemBankParentHoursFull,
        ItemBankLevelNotValid,
        NotFoundItembank,
        NotFoundParentOfItembank,
        ParentHoursmallerthan,
        BankHasPaper,
        InvalidParameter,
        parentILONotFound,
        ILONotFound,
        HoursExceeded,
        AppUserNotValid,
        UserNotAddedToGroup,
        UserShouldAtleastRelatedWithOneOrganization,
        NoChangesApplied,
        ItemBankAlreadyExist,
        ItemBankLevelAlreadyExist,
        PasswordNotMatched,
        InvalidOldPassword,
        InternalServerError,
        DuplicateGrouping,
        UserNotInAnyGroup,
        Failure,
        NoQuestionTypesFound,
        LayoutNotFounded,
        NoQuestion,
        ValidationError,
        QuestionAlreadyExist,
        NoQuestionMetadataFound,
        NoQuestionDetailsFound,
        NoDataToExport,
        NoQuestionsFound,
        GroupNotFound,
        Conflict,
        NotificationIsNotFound,
        Updated,
        BlockMismatch,
        EventIsPublished,
        AlreadyExist,
        AlreadyPublished,
        Nomatchingcandidatesfound,
        DistributionFail,
        MarkingSchemeSavedButQuestionSyncFailed,
        NotAllowed,
        DistributionSavedButQuestionSyncFailed,
        paperAndItsFormsSuspendedSuccessfully,
        FormSuspendedSuccessfully,
        PaperAlreadySuspended,
        PaperNotFound,
        FormNotFound,

        // WARNING: Don't change the indexes values of the enum members, to maintain integrity with the clients' CustomCodeStatus enums.
        UserNameOrPasswordNotValid = 1000,
        NoActiveOrganizations = 1001,
        SubscriptionNotFound = 1002,
        UnableToLogin = 1003,
        SomethingWentWrongSSO = 1004,
        UserHasMultipleOrganizations = 1005,
        AccountExpired = 1006,
        NotActiveUser = 1007,
        SamlNotAuthenticated = 1008,
        UserLockedOut = 1009,
        LocalAccessUserDenied = 1010,
    }
}
