namespace OES.Core.DatabaseObjects.Procedures.Encryption
{
    internal class EncryptionAndCompress
    {
        public string DropCommand => "DROP PROCEDURE IF EXISTS `sp_migrate_decrypted_column`";

        public string CreateCommand => @"
            DELIMITER $$

            CREATE TABLE IF NOT EXISTS migration_log (
                log_id                  INT AUTO_INCREMENT PRIMARY KEY,

                -- Groups all batches belonging to the same call together (UUID generated by the SP)
                run_id                  CHAR(36) NOT NULL,

                -- Type of operation: encrypt or decrypt
                operation_type          ENUM('ENCRYPT', 'DECRYPT') NOT NULL,

                -- Whether the call processed the whole table or a specific id range
                execution_mode          ENUM('FULL', 'RANGE') NOT NULL,

                table_name              VARCHAR(128) NOT NULL,
                column_name             VARCHAR(128) NOT NULL,

                -- Requested range from the caller (NULL when execution_mode = FULL)
                range_min_id            BIGINT NULL,
                range_max_id            BIGINT NULL,

                batch_number            INT NOT NULL,

                rows_scanned            INT NOT NULL DEFAULT 0,
                -- Rows actually modified in this batch (encrypted or decrypted, depending on operation_type)
                rows_affected            INT NOT NULL DEFAULT 0,
                -- Rows that were already in the target state before this batch touched them (already encrypted/decrypted)
                rows_already_processed  INT NOT NULL DEFAULT 0,
                rows_null_or_empty      INT NOT NULL DEFAULT 0,

                -- First and last id processed in this batch (useful for resuming an interrupted run)
                batch_first_id          BIGINT NULL,
                last_id_processed       BIGINT NULL,

                status                  ENUM('DRY_RUN_OK', 'COMMITTED', 'FAILED', 'SKIPPED_EMPTY') NOT NULL,
                error_message           TEXT NULL,

                KEY idx_run_id (run_id),
                KEY idx_table_column (table_name, column_name),
                KEY idx_status (status)
            );

            CREATE PROCEDURE sp_migrate_decrypted_column(
                IN p_table_name VARCHAR(128),
                IN p_pk_column VARCHAR(128),
                IN p_target_column VARCHAR(128),
                IN p_batch_size INT,
                IN p_dry_run TINYINT
            )
            BEGIN
                DECLARE v_enc_key VARCHAR(64);
                DECLARE v_enc_iv VARCHAR(64);
                DECLARE v_run_id CHAR(36);
                DECLARE v_last_id BIGINT DEFAULT 0;
                DECLARE v_max_id BIGINT DEFAULT 0;
                DECLARE v_batch_number INT DEFAULT 0;
                DECLARE v_rows_scanned INT;
                DECLARE v_rows_affected INT;
                DECLARE v_rows_already_processed INT;
                DECLARE v_rows_null_or_empty INT;
                DECLARE v_batch_max_id BIGINT;

                DECLARE EXIT HANDLER FOR SQLEXCEPTION
                BEGIN
                    ROLLBACK;
                    INSERT INTO migration_log
                        (run_id, operation_type, execution_mode, table_name, column_name,
                         range_min_id, range_max_id, batch_number, rows_scanned, rows_affected,
                         rows_already_processed, rows_null_or_empty, batch_first_id, last_id_processed,
                         status, error_message)
                    VALUES
                        (v_run_id, 'DECRYPT', 'FULL', p_table_name, p_target_column,
                         NULL, NULL, v_batch_number, 0, 0, 0, 0,
                         v_last_id + 1, v_last_id, 'FAILED',
                         'SQLException - this batch rolled back');
                    RESIGNAL;
                END;

                SET v_run_id = UUID();
                SET v_enc_key = 'VhZG9zTmVwYmUuSFBqpdG9yNj2lyYWF5';
                SET v_enc_iv  = 'lsUVJhR3VrcjVjUT';
                SET block_encryption_mode = 'aes-256-cbc';
                SET SESSION sql_safe_updates = 0;

                SET @sql = CONCAT('SELECT MAX(`', p_pk_column, '`) INTO @max_id FROM `', p_table_name, '`');
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
                SET v_max_id = @max_id;

                IF v_max_id IS NULL THEN
                    SELECT CONCAT('Table ', p_table_name, ' is empty or PK column not found') AS Message;
                ELSE
                    WHILE v_last_id < v_max_id DO

                        SET v_batch_number = v_batch_number + 1;

                        START TRANSACTION;

                        SET @sql = CONCAT(
                            'SELECT MAX(id_col) INTO @batch_max_id FROM (',
                            'SELECT `', p_pk_column, '` AS id_col ',
                            'FROM `', p_table_name, '` ',
                            'WHERE `', p_pk_column, '` > ', v_last_id, ' ',
                            'ORDER BY `', p_pk_column, '` ASC ',
                            'LIMIT ', p_batch_size,
                            ') AS batch_ids'
                        );
                        PREPARE stmt FROM @sql;
                        EXECUTE stmt;
                        DEALLOCATE PREPARE stmt;
                        SET v_batch_max_id = @batch_max_id;

                        IF v_batch_max_id IS NULL THEN
                            ROLLBACK;
                            SET v_last_id = v_max_id;
                        ELSE
                            -- Note: here ""rows_affected"" = rows to be decrypted, ""rows_already_processed"" = already decrypted
                            SET @sql = CONCAT(
                                'SELECT ',
                                'COUNT(*), ',
                                'SUM(CASE WHEN `', p_target_column, '` IS NULL OR `', p_target_column, '` = '''' THEN 1 ELSE 0 END), ',
                                'SUM(CASE WHEN `', p_target_column, '` IS NOT NULL AND `', p_target_column, '` <> '''' ',
                                'AND CAST(UNCOMPRESS(AES_DECRYPT(FROM_BASE64(`', p_target_column, '`), ', QUOTE(v_enc_key), ', ', QUOTE(v_enc_iv), ')) AS CHAR) IS NULL ',
                                'THEN 1 ELSE 0 END), ',
                                'SUM(CASE WHEN `', p_target_column, '` IS NOT NULL AND `', p_target_column, '` <> '''' ',
                                'AND CAST(UNCOMPRESS(AES_DECRYPT(FROM_BASE64(`', p_target_column, '`), ', QUOTE(v_enc_key), ', ', QUOTE(v_enc_iv), ')) AS CHAR) IS NOT NULL ',
                                'THEN 1 ELSE 0 END) ',
                                'INTO @rows_scanned, @rows_null_or_empty, @rows_already_processed, @rows_affected ',
                                'FROM `', p_table_name, '` ',
                                'WHERE `', p_pk_column, '` > ', v_last_id,
                                ' AND `', p_pk_column, '` <= ', v_batch_max_id
                            );
                            PREPARE stmt FROM @sql;
                            EXECUTE stmt;
                            DEALLOCATE PREPARE stmt;

                            SET v_rows_scanned = @rows_scanned;
                            SET v_rows_null_or_empty = @rows_null_or_empty;
                            SET v_rows_already_processed = @rows_already_processed;
                            SET v_rows_affected = @rows_affected;

                            IF p_dry_run = 0 THEN
                                SET @sql = CONCAT(
                                    'UPDATE `', p_table_name, '` ',
                                    'SET `', p_target_column, '` = ',
                                    'CAST(UNCOMPRESS(AES_DECRYPT(FROM_BASE64(`', p_target_column, '`), ', QUOTE(v_enc_key), ', ', QUOTE(v_enc_iv), ')) AS CHAR) ',
                                    'WHERE `', p_pk_column, '` > ', v_last_id,
                                    ' AND `', p_pk_column, '` <= ', v_batch_max_id,
                                    ' AND `', p_target_column, '` IS NOT NULL ',
                                    'AND `', p_target_column, '` <> '''' ',
                                    'AND CAST(UNCOMPRESS(AES_DECRYPT(FROM_BASE64(`', p_target_column, '`), ', QUOTE(v_enc_key), ', ', QUOTE(v_enc_iv), ')) AS CHAR) IS NOT NULL'
                                );
                                PREPARE stmt FROM @sql;
                                EXECUTE stmt;
                                DEALLOCATE PREPARE stmt;
                            END IF;

                            COMMIT;

                            INSERT INTO migration_log
                                (run_id, operation_type, execution_mode, table_name, column_name,
                                 range_min_id, range_max_id, batch_number, rows_scanned, rows_affected,
                                 rows_already_processed, rows_null_or_empty, batch_first_id, last_id_processed,
                                 status)
                            VALUES
                                (v_run_id, 'DECRYPT', 'FULL', p_table_name, p_target_column,
                                 NULL, NULL, v_batch_number, v_rows_scanned, v_rows_affected,
                                 v_rows_already_processed, v_rows_null_or_empty, v_last_id + 1, v_batch_max_id,
                                 IF(p_dry_run = 1, 'DRY_RUN_OK', 'COMMITTED'));

                            SET v_last_id = v_batch_max_id;
                        END IF;

                    END WHILE;

                    SELECT CONCAT('DONE: ', p_table_name, '.', p_target_column) AS Message,
                           v_batch_number AS TotalBatches, v_run_id AS RunId;
                END IF;

            END$$

            DELIMITER;
        ";
    }
}