using Blazored.LocalStorage;
using Blazored.SessionStorage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor.Services;
using OES.Blazor.CustomAuthorizationAttribute;
using OES.Blazor.Services;
using OES.Blazor.Services.Implementation;
using OES.Blazor.Services.Implementation.AIFeatures;
using OES.Blazor.Services.Implementation.AppUser;
using OES.Blazor.Services.Implementation.AuditLogs;
using OES.Blazor.Services.Implementation.AuthServices;
using OES.Blazor.Services.Implementation.Block;
using OES.Blazor.Services.Implementation.Candidate;
using OES.Blazor.Services.Implementation.CandidatesResult;
using OES.Blazor.Services.Implementation.CBTSyncSettingService;
using OES.Blazor.Services.Implementation.Common;
using OES.Blazor.Services.Implementation.DeltaType;
using OES.Blazor.Services.Implementation.DifficultyLevel;
using OES.Blazor.Services.Implementation.DifficultyProfile;
using OES.Blazor.Services.Implementation.Disability;
using OES.Blazor.Services.Implementation.DocLibHttpClientHelperService;
using OES.Blazor.Services.Implementation.DocumentService;
using OES.Blazor.Services.Implementation.EquationTemplate;
using OES.Blazor.Services.Implementation.FileExportService;
using OES.Blazor.Services.Implementation.FolderService;
using OES.Blazor.Services.Implementation.FormService;
using OES.Blazor.Services.Implementation.Group;
using OES.Blazor.Services.Implementation.GroupTempelates;
using OES.Blazor.Services.Implementation.GroupWizard;
using OES.Blazor.Services.Implementation.GRPC;
using OES.Blazor.Services.Implementation.ILOSection;
using OES.Blazor.Services.Implementation.ItemBank;
using OES.Blazor.Services.Implementation.ItemBankLevels;
using OES.Blazor.Services.Implementation.ItemBankPoint;
using OES.Blazor.Services.Implementation.Language;
using OES.Blazor.Services.Implementation.MarkingScheme;
using OES.Blazor.Services.Implementation.MediaSettingService;
using OES.Blazor.Services.Implementation.MemoryCache;
using OES.Blazor.Services.Implementation.Notification;
using OES.Blazor.Services.Implementation.OrganizationStructureService;
using OES.Blazor.Services.Implementation.PagesService;
using OES.Blazor.Services.Implementation.Paper;
using OES.Blazor.Services.Implementation.Paper.Transition;
using OES.Blazor.Services.Implementation.PathsService;
using OES.Blazor.Services.Implementation.PdfGeneratorService;
using OES.Blazor.Services.Implementation.QComment;
using OES.Blazor.Services.Implementation.QualityCheckCommitteeService;
using OES.Blazor.Services.Implementation.Question;
using OES.Blazor.Services.Implementation.QuestionCategory;
using OES.Blazor.Services.Implementation.QuestionLanguage;
using OES.Blazor.Services.Implementation.QuestionLayout;
using OES.Blazor.Services.Implementation.QuestionMetaDataService;
using OES.Blazor.Services.Implementation.QuestionType;
using OES.Blazor.Services.Implementation.QuestionUploadTemplateService;
using OES.Blazor.Services.Implementation.Report;
using OES.Blazor.Services.Implementation.RolesService;
using OES.Blazor.Services.Implementation.Schedule;
using OES.Blazor.Services.Implementation.ScheduleSecurityConfigurationsService;
using OES.Blazor.Services.Implementation.Section;
using OES.Blazor.Services.Implementation.SessionStorageService;
using OES.Blazor.Services.Implementation.Subject;
using OES.Blazor.Services.Implementation.SubQuestion;
using OES.Blazor.Services.Implementation.Template;
using OES.Blazor.Services.Implementation.TemplateSubmission;
using OES.Blazor.Services.Implementation.TransitionProfile;
using OES.Blazor.Services.Implementation.UploadFile;
using OES.Blazor.Services.Implementation.UserService;
using OES.Blazor.Services.Implementation.Venue;
using OES.Blazor.Services.Interfaces;
using OES.Blazor.Services.Interfaces.AIFeatures;
using OES.Blazor.Services.Interfaces.AppUser;
using OES.Blazor.Services.Interfaces.AuditLogs;
using OES.Blazor.Services.Interfaces.AuthServices;
using OES.Blazor.Services.Interfaces.Block;
using OES.Blazor.Services.Interfaces.Candidate;
using OES.Blazor.Services.Interfaces.CandidatesResult;
using OES.Blazor.Services.Interfaces.CBTSyncSettingService;
using OES.Blazor.Services.Interfaces.Common;
using OES.Blazor.Services.Interfaces.DeltaType;
using OES.Blazor.Services.Interfaces.DifficultyLevel;
using OES.Blazor.Services.Interfaces.DifficultyProfile;
using OES.Blazor.Services.Interfaces.Disability;
using OES.Blazor.Services.Interfaces.DocumentService;
using OES.Blazor.Services.Interfaces.EquationTemplate;
using OES.Blazor.Services.Interfaces.FileExportService;
using OES.Blazor.Services.Interfaces.FolderService;
using OES.Blazor.Services.Interfaces.Form;
using OES.Blazor.Services.Interfaces.Group;
using OES.Blazor.Services.Interfaces.GroupsTempleates;
using OES.Blazor.Services.Interfaces.GroupWizard;
using OES.Blazor.Services.Interfaces.GRPC;
using OES.Blazor.Services.Interfaces.ILOSection;
using OES.Blazor.Services.Interfaces.ISessionStorageService;
using OES.Blazor.Services.Interfaces.ItemBank;
using OES.Blazor.Services.Interfaces.ItemBankLevels;
using OES.Blazor.Services.Interfaces.ItemBankPoint;
using OES.Blazor.Services.Interfaces.Language;
using OES.Blazor.Services.Interfaces.MarkingScheme;
using OES.Blazor.Services.Interfaces.MediaSettingService;
using OES.Blazor.Services.Interfaces.MemoryCache;
using OES.Blazor.Services.Interfaces.Notification;
using OES.Blazor.Services.Interfaces.OrganizationStructureService;
using OES.Blazor.Services.Interfaces.PagesService;
using OES.Blazor.Services.Interfaces.Paper;
using OES.Blazor.Services.Interfaces.Paper.Transition;
using OES.Blazor.Services.Interfaces.PathsService;
using OES.Blazor.Services.Interfaces.PdfGeneratorService;
using OES.Blazor.Services.Interfaces.QComment;
using OES.Blazor.Services.Interfaces.QualityCheckCommittee;
using OES.Blazor.Services.Interfaces.Question;
using OES.Blazor.Services.Interfaces.QuestionCataegory;
using OES.Blazor.Services.Interfaces.Questionlanguage;
using OES.Blazor.Services.Interfaces.QuestionLayout;
using OES.Blazor.Services.Interfaces.QuestionMetaData;
using OES.Blazor.Services.Interfaces.QuestionType;
using OES.Blazor.Services.Interfaces.QuestionUploadTemplate;
using OES.Blazor.Services.Interfaces.Report;
using OES.Blazor.Services.Interfaces.RolesService;
using OES.Blazor.Services.Interfaces.Schedule;
using OES.Blazor.Services.Interfaces.ScheduleSecurityConfigurationsService;
using OES.Blazor.Services.Interfaces.Section;
using OES.Blazor.Services.Interfaces.Subject;
using OES.Blazor.Services.Interfaces.SubQuestion;
using OES.Blazor.Services.Interfaces.Template;
using OES.Blazor.Services.Interfaces.TemplateSubmission;
using OES.Blazor.Services.Interfaces.TransitionProfile;
using OES.Blazor.Services.Interfaces.UploadFile;
using OES.Blazor.Services.Interfaces.UserService;
using OES.Blazor.Services.Interfaces.Venue;
using OES.Helper.Dtos;
using OES.Helper.General;
using OES.Helper.General.GlobalUserContext;
using OES.Helper.Interfaces;
using SharedHelper.General;
using System.Globalization;
using System.Net.Http.Headers;

namespace OES.Blazor.Extensions
{
    public static class DependencyInjection
    {
        public static IServiceCollection RegisterServices(this IServiceCollection Services, IWebAssemblyHostEnvironment hostEnvironment)
        {
            Services.AddScoped(typeof(IApiResponse), typeof(ApiResponse));
            Services.AddScoped(typeof(IHttpClientHelper), typeof(HttpClientHelper));
            Services.AddScoped(typeof(IBlazItemBankService), typeof(BlazItemBankService));
            Services.AddScoped<IBlazUserProfileService, BlazUserProfileService>();
            Services.AddScoped(typeof(IBlazorItemBankLevelsService), typeof(BlazorItemBankLevelsService));
            Services.AddScoped(typeof(IBlazGetCustomTableData<>), typeof(BlazGetCustomTableDataService<>));
            Services.AddScoped<IBlazILOService, BlazILOService>();
            Services.AddTransient(typeof(IPaginationSearchModel), typeof(PaginationSearchModel));
            Services.AddMudServices();
            Services.AddScoped<CRUD_Dto>();
            Services.AddMemoryCache();
            Services.AddBlazoredLocalStorage();
            Services.AddBlazoredSessionStorage();
            Services.AddScoped<IBlazSessionStorageService, SessionStorageService>();
            Services.AddScoped<IGetPagesService, GetPagesService>();
            Services.AddScoped<IBlazPagesService, BlazPagesService>();
            Services.AddScoped<IBlazPathsService, BlazPathsService>();
            Services.AddScoped<IBlazRolesService, BlazRolesService>();
            Services.AddScoped<IBlazMemoryCache, BlazMemoryCache>();
            Services.AddScoped<IItemBankTreeGrpcService, ItemBankTreeGrpcService>();
            Services.AddScoped<IILoTreeGrpcService, ILoTreeGrpcService>();
            Services.AddScoped<IBlazQuestionCategoryService, BlazQuestionCategoryService>();
            Services.AddScoped<IBlazLanguageService, BlazLanguageService>();
            Services.AddScoped<IBlazDifficultyProfileService, BlazDifficultyProfileService>();
            Services.AddScoped<IBlazOesRoleTemplateService, BlazOesRoleTemplateService>();
            Services.AddScoped<IBlazDeltaTypeService, BlazDeltaTypeService>();
            Services.AddScoped<IBlazQuestionService, BlazQuestionService>();
            Services.AddScoped<IBlazGroupService, BlazGroupService>();
            Services.AddScoped<IBlazUserProfileService, BlazUserProfileService>();
            Services.AddScoped<IBlazSubjectService, BlazSubjectService>();
            Services.AddScoped<IBlazQuestionLayoutService, BlazQuestionLayoutService>();
            Services.AddScoped<IBlazQuestionLanguageService, BlazQuestionLanguageService>();
            Services.AddScoped<IBlazSubQuestionService, BlazSubQuestionService>();
            Services.AddScoped<IBlazQuestionMetaData, BlazQuestionMetaDataService>();
            Services.AddScoped<IBlazUploadFileService, BlazUploadFileService>();
            Services.AddScoped<ISyncToExamServer, SyncToExamServer>();
            Services.AddScoped<IBlazSyncToEvaluation, BlazSyncToEvaluation>();
            Services.AddScoped<IBlazQuestionUploadTemplateService, BlazQuestionUploadTemplateService>();
            Services.AddScoped<IBlazQualityCheckCommitteeService, BlazQualityCheckCommitteeService>();
            Services.AddScoped<IBlazDisabilityService, BlazDisabilityService>();
            Services.AddTransient<AuthorizationMessageHandler>();
            Services
                .AddHttpClient("OesApi", client =>
                {
                    client.BaseAddress = new Uri(CentralizedUrlHelper.OesApiBaseUrl);
                    var currentCulture = CultureInfo.CurrentCulture.Name;
                    client.DefaultRequestHeaders.AcceptLanguage.Clear();
                    client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue(currentCulture));
                })
                .AddHttpMessageHandler<AuthorizationMessageHandler>();
            Services
                .AddHttpClient("DocLibApi", client =>
                {
                    client.BaseAddress = new Uri(CentralizedUrlHelper.DocLibApiBaseUrl);
                    var currentCulture = CultureInfo.CurrentCulture.Name;
                    client.DefaultRequestHeaders.AcceptLanguage.Clear();
                    client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue(currentCulture));
                })
                .AddHttpMessageHandler<AuthorizationMessageHandler>();
            Services.AddScoped<IBlazFolderService, BlazFolderService>();
            Services.AddScoped<IBlazDocumentService, BlazDocumentService>();
            Services.AddScoped<DocLibHttpClientHelper>();
            Services.AddScoped<IBlazUserService, BlazUserService>();
            Services.AddScoped<IBlazFileExportService, BlazFileExportService>();
            Services.AddScoped<IBLazQuestionType, BLazQuestionType>();
            Services.AddScoped<IBlazQCommentService, BlazQCommentService>();
            Services.AddScoped<IBlazDifficultyLevelService, BlazDifficultyLevelService>();
            Services.AddScoped<IBlazNotificationService, BlazNotificationService>();
            Services.AddScoped<INotificationManager, NotificationManager>();
            Services.AddScoped<IBlazBlockService, BlazBlockService>();
            Services.AddScoped<IBlazPaperService, BlazPaperService>();
            Services.AddScoped<IBlazMarkingSchemeService, BlazMarkingSchemeService>();
            Services.AddScoped<IBlazTemplateService, BlazTemplateService>();
            Services.AddScoped<IBlazTransitionProfileService, BlazTransitionProfileService>();
            Services.AddScoped<IBlazTransitionLevelService, BlazTransitionLevelService>();
            Services.AddScoped<IBlazPaperSummaryService, BlazPaperSummaryService>();
            Services.AddScoped<IBlazItemBankPointService, BlazItemBankPointService>();
            Services.AddScoped<IBlazSecurityConfigurationsService, BlazSecurityConfigurationsService>();
            Services.AddScoped<IBlazScheduleService, BlazScheduleService>();
            Services.AddScoped<IBlazTemplateSubmissionService, TemplateSubmissionService>();
            Services.AddScoped<IBlazVenueService, BlazVenueService>();
            Services.AddScoped<IBlazCandidateService, BlazCandidateService>();
            Services.AddScoped<IBlazPaperSettingsService, BlazPaperSettingsService>();
            Services.AddScoped<IBlazOrganizationStructureService, BlazOrganizationStructureService>();
            Services.AddScoped<IBlazSchedulePaperService, BlazSchedulePaperService>();
            Services.AddScoped<IBlazQuestionDistributionValidationService, BlazQuestionDistributionValidationService>();
            Services.AddScoped<IBlazFormQuestionScoreService, BlazFormQuestionScoreService>();
            Services.AddScoped<IBlazFormService, BlazFormService>();
            Services.AddScoped<IBlazSectionService, BlazSectionService>();
            Services.AddScoped<IBlazQuestionInstructionTemplate, BlazQuestionInstructionTemplateService>();
            Services.AddScoped<IBlazDashboardService, BlazDashboardService>();
            Services.AddScoped<IBlazCandidatesResultService, BlazCandidatesResultService>();
            Services.AddSingleton<IComponentActivator, CustomComponentActivator>();
            Services.AddScoped<IBlazEquationTemplateService, BlazEquationTemplateService>();
            Services.AddScoped<IBlazePdfGeneratorService, BlazePdfGeneratorService>();
            Services.AddScoped<IBlazQueueSuspendService, BlazQueueSuspendService>();
            Services.AddScoped<IBlazMediaSettingService, BlazMediaSettingService>();
            Services.AddScoped<IBlazCBTSyncSettingService, BlazCBTSyncSettingService>();
            Services.AddScoped<IBlazAnalyticalReportsService, BlazAnalyticalReportsService>();
            Services.AddScoped<IBlazVerificationReportsService, BlazVerificationReportsService>();
            Services.AddScoped<IBlazResultsReportsService, BlazResultsReportsService>();
            Services.AddScoped<IBlazAIFeatureAccessService, BlazAIFeatureAccessService>();
            Services.AddScoped<IBlazAIQuestionGenerationService, BlazAIQuestionGenerationService>();
            Services.AddScoped<IBlazAIItemBankGenerationService, BlazAIItemBankGenerationService>();
            Services.AddScoped<IBlazAuditLogsService, BlazAuditLogsService>();
            Services.AddScoped<IGroupWizardResourceService, GroupWizardResourceService>();
            Services.AddMudBlazorConfiguration();

            /* AUTHENTICATION & AUTHORIZATION */

            Services.AddScoped<IBlazAuthService, BlazAuthService>();
            Services.AddScoped<GlobalUserContext>();
            Services.AddScoped<CustomAuthStateProvider>();
            Services.AddScoped<AuthenticationStateProvider>(provider => provider.GetRequiredService<CustomAuthStateProvider>());
            Services.AddCascadingAuthenticationState();
            Services.AddAuthorizationCore();
            Services.AddSingleton<IAuthorizationPolicyProvider, DynamicAuthorizationPolicyProvider>();
            Services.AddScoped<IAuthorizationHandler, DynamicRolesHandler>();
            Services.AddSingleton<ISyncStatusService, SyncStatusService>();
            Services.AddSingleton<SyncDashboardState>();
            Services.AddSingleton(hostEnvironment);

            return Services;
        }
    }
}