using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using OES.Blazor.InternalHelperTypes.General;
using OES.Blazor.Services;
using OES.Blazor.Services.Interfaces.Report;
using OES.Helper.Dtos.Reports;
using OES.Helper.Dtos.Reports.Analytical;
using OES.Helper.General;
using OES.Helper.ResourceFiles;
using System.Globalization;
using System.Text;

namespace OES.Blazor.Pages.Reports
{
    public partial class ScoreDistributionReport
    {
        private static readonly string _infoOverview = Resource.ScoreDistributionReportOverview;

        private static readonly List<ReportInfoSection> _infoSections =
        [
            new ReportInfoSection(Resource.RptSD_SectionStatCards,
            [
                new ReportInfoItem(Resource.RptSD_TotalCandidates, Resource.RptSD_TotalCandidatesDesc),
                new ReportInfoItem(Resource.RptSD_Pass, Resource.RptSD_PassDesc),
                new ReportInfoItem(Resource.RptSD_Fail, Resource.RptSD_FailDesc),
                new ReportInfoItem(Resource.RptSD_PassRate, Resource.RptSD_PassRateDesc),
                new ReportInfoItem(Resource.RptMean, Resource.RptSD_MeanDesc),
                new ReportInfoItem(Resource.RptMedian, Resource.RptSD_MedianDesc),
                new ReportInfoItem(Resource.RptMode, Resource.RptSD_ModeDesc),
                new ReportInfoItem(Resource.RptStdDeviation, Resource.RptSD_StdDevDesc),
                new ReportInfoItem(Resource.RptSD_MinMax, Resource.RptSD_MinMaxDesc),
                new ReportInfoItem(Resource.RptSkewness, Resource.RptSD_SkewnessDesc),
                new ReportInfoItem(Resource.RptKurtosis, Resource.RptSD_KurtosisDesc),
            ]),
            new ReportInfoSection(Resource.RptSD_SectionHistogram,
            [
                new ReportInfoItem(Resource.RptItemBars, Resource.RptSD_BarsDesc),
                new ReportInfoItem(Resource.RptSD_GreenBars, Resource.RptSD_GreenBarsDesc),
                new ReportInfoItem(Resource.RptSD_RedBars, Resource.RptSD_RedBarsDesc),
                new ReportInfoItem(Resource.RptSD_DashedLine, Resource.RptSD_DashedLineDesc),
                new ReportInfoItem(Resource.RptSD_HoverTooltip, Resource.RptSD_HoverTooltipDesc),
            ]),
            new ReportInfoSection(Resource.RptSD_SectionPercentileTable,
            [
                new ReportInfoItem(Resource.RptSD_P10, Resource.RptSD_P10Desc),
                new ReportInfoItem(Resource.RptSD_Q1P25, Resource.RptSD_Q1P25Desc),
                new ReportInfoItem(Resource.RptSD_P50Median, Resource.RptSD_P50MedianDesc),
                new ReportInfoItem(Resource.RptSD_Q3P75, Resource.RptSD_Q3P75Desc),
                new ReportInfoItem(Resource.RptSD_P90, Resource.RptSD_P90Desc),
            ]),
            new ReportInfoSection(Resource.RptSD_SectionScoreBand,
            [
                new ReportInfoItem(Resource.RptSD_Bands, Resource.RptSD_BandsDesc),
                new ReportInfoItem(Resource.RptSD_HighlightedRow, Resource.RptSD_HighlightedRowDesc),
                new ReportInfoItem(Resource.RptSD_InlineBar, Resource.RptSD_InlineBarDesc),
            ]),
            new ReportInfoSection(Resource.RptSD_SectionInterpretation,
            [
                new ReportInfoItem(Resource.RptSD_AutoGeneratedSummary, Resource.RptSD_AutoGeneratedSummaryDesc),
            ]),
        ];

        private IEnumerable<StatCard> StatCards
        {
            get
            {
                if (_report == null) yield break;
                yield return new StatCard(Resource.RptTotalCandidates, _report.TotalCandidates.ToString());
                yield return new StatCard(Resource.RptPass, _report.PassCount.ToString(), "color:#4CAF50;font-weight:600");
                yield return new StatCard(Resource.RptFail, _report.FailCount.ToString(), "color:#F44336;font-weight:600");
                var passColor = _report.PassRate >= 80 ? "#4CAF50" : _report.PassRate >= 50 ? "#FF9800" : "#F44336";
                yield return new StatCard(Resource.RptPassRate, $"{_report.PassRate}%", $"color:{passColor};font-weight:600");
                yield return new StatCard(Resource.RptMean, _report.Mean.ToString("F1"));
                yield return new StatCard(Resource.RptMedian, _report.Median.ToString("F1"));
                yield return new StatCard(Resource.RptMode, _report.Mode.ToString("F1"));
                yield return new StatCard(Resource.RptStdDeviation, _report.StdDev.ToString("F1"));
                yield return new StatCard(Resource.RptMinScore, _report.Min.ToString("F0"));
                yield return new StatCard(Resource.RptMaxScore, _report.Max.ToString("F0"));
                yield return new StatCard(Resource.RptSkewness, _report.Skewness.ToString("F2"), "", _report.SkewnessInterpretation);
                yield return new StatCard(Resource.RptKurtosis, _report.Kurtosis.ToString("F2"), "", _report.KurtosisInterpretation);
            }
        }

        [Inject] private IBlazResultsReportsService ResultsReportsService { get; set; } = default!;
        [Inject] private IJSRuntime JS { get; set; } = default!;

        private List<PaperLookupDto> _papers = [];
        private List<FormLookupDto> _forms = [];
        private ScoreDistributionReportDto? _report;

        private PaperLookupDto? _selectedPaper;
        private IEnumerable<FormLookupDto> _selectedForms = [];
        private DateTime? _startDate;
        private DateTime? _endDate;
        private double _cutScore = 60;

        private bool _isLoading;
        private bool _isExporting;
        private string? _errorMessage;
        private string? _noDataMessage;
        private MarkupString? _histogramSvgCache;

        public Func<PaperLookupDto, string> PaperToString = p => p == null ? string.Empty : $"{p.Code} - {p.Name}";
        public Func<FormLookupDto, string> FormToString = f => f == null ? string.Empty : $"{f.Code} - {f.Name}";
        readonly bool isRtl = CultureInfo.CurrentUICulture.TextInfo.IsRightToLeft;

        // SVG layout constants
        private const int PL = 55;
        private const int PT = 35;
        private const int PR = 20;
        private const int PB = 65;
        private const int SvgWidth = 800;
        private const int SvgHeight = 420;

        private double PlotWidth => SvgWidth - PL - PR;
        private double PlotHeight => SvgHeight - PT - PB;
        private double BarWidth => _report?.Bins.Count > 0 ? PlotWidth / _report.Bins.Count : 0;
        private double CutScoreX => _report == null || _report.TotalMarks == 0 ? PL : PL + (_report.CutScore / _report.TotalMarks) * PlotWidth;
        private IEnumerable<YAxisTick> YAxisTicks
        {
            get
            {
                if (_report == null || _report.Bins.Count == 0) yield break;

                double maxCount = _report.Bins.Max(b => (double)b.Count);

                if (maxCount == 0) yield break;

                for (int i = 0; i <= 4; i++)
                {
                    double value = maxCount * i / 4.0;
                    double y = PT + PlotHeight * (1.0 - i / 4.0);
                    yield return new YAxisTick(y, ((int)Math.Round(value)).ToString());
                }
            }
        }
        private MarkupString HistogramSvg => _histogramSvgCache ??= BuildHistogramSvg();


        private double BinX(int idx) => PL + idx * BarWidth;

        private async Task ExportAsync()
        {
            if (_report == null)
            {
                return;
            }

            _isExporting = true;

            try
            {
                var summarySheet = BuildSummarySheet();

                var percentileSheet = BuildPercentileSheet();

                var bandSheet = BuildBandSheet();

                var (bytes, extension) = ReportExportHelper.Build(
                    Resource.RptTitleScoreDistribution,
                    summarySheet,
                    percentileSheet,
                    bandSheet);

                await JS.InvokeVoidAsync("downloadFileFromBytes", bytes, $"Score_Distribution_Report.{extension}");
            }
            finally
            {
                _isExporting = false;
            }
        }

        private double BinHeight(int count)
        {
            if (_report == null || _report.Bins.Count == 0)
            {
                return 0;
            }

            double maxCount = _report.Bins.Max(b => (double)b.Count);
            return maxCount == 0 ? 0 : count / maxCount * PlotHeight;
        }

        private MarkupString BuildHistogramSvg()
        {
            if (_report == null) return new MarkupString(string.Empty);

            double maxCount = _report.Bins.Count > 0 ? _report.Bins.Max(b => (double)b.Count) : 1;

            if (maxCount == 0) maxCount = 1;

            var sb = new StringBuilder();
            sb.Append($"<svg viewBox=\"0 0 {SvgWidth} {SvgHeight}\" style=\"width:100%;display:block\"xmlns=\"http://www.w3.org/2000/svg\">");

            // Y-axis ticks + grid lines
            for (int i = 0; i <= 4; i++)
            {
                double value = maxCount * i / 4.0;
                double y = PT + PlotHeight * (1.0 - i / 4.0);
                int label = (int)Math.Round(value);
                sb.Append($"<line x1=\"{PL}\" y1=\"{y:F1}\" x2=\"{PL - 5}\" y2=\"{y:F1}\" stroke=\"#999\" stroke-width=\"1\"/>");
                sb.Append($"<text x=\"{PL - 8}\" y=\"{y:F1}\" text-anchor=\"end\" dominant-baseline=\"middle\" font-size=\"11\" fill=\"#555\">{label}</text>");
                sb.Append($"<line x1=\"{PL}\" y1=\"{y:F1}\" x2=\"{SvgWidth - PR}\" y2=\"{y:F1}\" stroke=\"#eee\" stroke-width=\"1\"/>");
            }

            // Bars
            for (int i = 0; i < _report.Bins.Count; i++)
            {
                var bin = _report.Bins[i];
                double bx = BinX(i);
                double bh = bin.Count / maxCount * PlotHeight;
                double by = PT + PlotHeight - bh;
                string fill = bin.IsPassZone ? "#4CAF50" : "#F44336";
                string tooltip = System.Net.WebUtility.HtmlEncode($"{bin.Label} — {bin.Count} candidates ({bin.Percentage}%)");
                sb.Append($"<rect x=\"{bx:F1}\" y=\"{by:F1}\" width=\"{BarWidth - 2:F1}\" height=\"{bh:F1}\" fill=\"{fill}\" opacity=\"0.85\" rx=\"2\"><title>{tooltip}</title></rect>");
            }

            // X-axis bin labels
            for (int i = 0; i < _report.Bins.Count; i++)
            {
                double lx = BinX(i) + BarWidth / 2;
                double ly = PT + PlotHeight + 10;
                var anchor = isRtl ? "start" : "end";
                var rotate = isRtl ? 40 : -40;
                sb.Append($"<text x=\"{lx:F1}\" y=\"{ly:F1}\" text-anchor=\"{anchor}\" font-size=\"10\" fill=\"#555\" direction=\"{(isRtl ? "rtl" : "ltr")}\" transform=\"rotate({rotate} {lx:F1} {ly:F1})\">{_report.Bins[i].Label}</text>");
            }

            // Axes
            sb.Append($"<line x1=\"{PL}\" y1=\"{PT}\" x2=\"{PL}\" y2=\"{PT + PlotHeight}\" stroke=\"#999\" stroke-width=\"1.5\"/>");
            sb.Append($"<line x1=\"{PL}\" y1=\"{PT + PlotHeight}\" x2=\"{SvgWidth - PR}\" y2=\"{PT + PlotHeight}\" stroke=\"#999\" stroke-width=\"1.5\"/>");

            // Cut score line
            double cx = CutScoreX;
            sb.Append($"<line x1=\"{cx:F1}\" y1=\"{PT - 5}\" x2=\"{cx:F1}\" y2=\"{PT + PlotHeight}\" stroke=\"#333\" stroke-width=\"2\" stroke-dasharray=\"6,4\"/>");
            sb.Append($"<text x=\"{cx + 4:F1}\" y=\"{PT + 8}\" font-size=\"11\" fill=\"#333\" font-weight=\"bold\">Cut: {_report.CutScore}</text>");

            // Legend
            if (isRtl)
            {
                sb.Append($"<text x=\"{SvgWidth - PR - 130}\" y=\"{PT + 10}\" text-anchor=\"start\" font-size=\"11\" fill=\"#555\">{Resource.RptFail}</text>");
                sb.Append($"<rect x=\"{SvgWidth - PR - 160}\" y=\"{PT}\" width=\"12\" height=\"12\" fill=\"#F44336\" rx=\"2\"/>");

                sb.Append($"<text x=\"{SvgWidth - PR - 60}\" y=\"{PT + 10}\" text-anchor=\"start\" font-size=\"11\" fill=\"#555\">{Resource.RptPass}</text>");
                sb.Append($"<rect x=\"{SvgWidth - PR - 90}\" y=\"{PT}\" width=\"12\" height=\"12\" fill=\"#4CAF50\" rx=\"2\"/>");
            }
            else
            {
                sb.Append($"<rect x=\"{SvgWidth - PR - 130}\" y=\"{PT}\" width=\"12\" height=\"12\" fill=\"#F44336\" rx=\"2\"/>");
                sb.Append($"<text x=\"{SvgWidth - PR - 114}\" y=\"{PT + 10}\" font-size=\"11\" fill=\"#555\">{Resource.RptFail}</text>");

                sb.Append($"<rect x=\"{SvgWidth - PR - 60}\" y=\"{PT}\" width=\"12\" height=\"12\" fill=\"#4CAF50\" rx=\"2\"/>");
                sb.Append($"<text x=\"{SvgWidth - PR - 44}\" y=\"{PT + 10}\" font-size=\"11\" fill=\"#555\">{Resource.RptPass}</text>");
            }

            sb.Append("</svg>");
            return new MarkupString(sb.ToString());
        }

        protected override async Task OnInitializedAsync()
        {
            _papers = await ResultsReportsService.GetItemAnalysisPapersAsync();
        }

        private async Task<IEnumerable<PaperLookupDto>> SearchPapersAsync(string value, CancellationToken cancellationToken)
        {
            await Task.Delay(200, cancellationToken);

            if (string.IsNullOrEmpty(value))
            {
                return _papers;
            }

            return _papers.Where(p =>
                (p.Code?.Contains(value, StringComparison.InvariantCultureIgnoreCase) ?? false) ||
                (p.Name?.Contains(value, StringComparison.InvariantCultureIgnoreCase) ?? false));
        }

        private async Task OnPaperChangedAsync(PaperLookupDto paper)
        {
            _selectedPaper = paper;
            _selectedForms = [];
            _forms = [];

            ResetReport();

            if (paper != null)
            {
                _forms = await ResultsReportsService.GetItemAnalysisFormsAsync(paper.Code);
            }

            StateHasChanged();
        }

        private Task OnFormsChangedAsync(IEnumerable<FormLookupDto> forms)
        {
            _selectedForms = forms;

            ResetReport();

            return Task.CompletedTask;
        }

        private async Task GenerateReportAsync()
        {
            if (_selectedPaper == null || !_selectedForms.Any())
            {
                return;
            }

            _isLoading = true;

            ResetReport();

            try
            {
                _report = await ResultsReportsService.GetScoreDistributionReportAsync(new(
                    [.. _selectedForms.Select(x => x.Id)],
                    _cutScore,
                    new PaginationSearchModel
                    {
                        PaginationOff = true,
                        FromDate = _startDate,
                        ToDate = _endDate
                    }));

                _histogramSvgCache = null;
            }
            catch (Exception ex)
            {
                var message = ex.Message;

                if (message.StartsWith(Resource.RptNoCompletedSessions) || message.StartsWith(Resource.RptNoResponsesFound))
                {
                    _noDataMessage = message;
                }
                else
                {
                    _errorMessage = string.Format(Resource.RptFailedToLoad, message);
                }
            }
            finally
            {
                _isLoading = false;
            }
        }

        private ExportSheet BuildSummarySheet()
        {
            return new(
                Resource.RptTitleScoreDistribution,
                [Resource.RptMetric, Resource.RptValue],
                [
                    [Resource.RptPaperLabel, _report!.PaperName],
                    [Resource.Form, _report.FormName],
                    [Resource.RptTotalMarks,_report.TotalMarks],
                    [Resource.RptCutScore,_report.CutScore],
                    [Resource.RptTotalCandidates, _report.TotalCandidates],
                    [Resource.RptPass, _report.PassCount],
                    [Resource.RptFail, _report.FailCount],
                    [Resource.RptPassRate, _report.PassRate],
                    [Resource.RptMean, _report.Mean],
                    [Resource.RptMedian, _report.Median],
                    [Resource.RptMode, _report.Mode],
                    [Resource.RptStdDeviation, _report.StdDev],
                    [Resource.RptMinScore,_report.Min],
                    [Resource.RptMaxScore, _report.Max],
                    [Resource.RptSkewness, _report.Skewness],
                    [Resource.RptKurtosis,_report.Kurtosis],
                    [Resource.RptDistributionShapeInterpretation, _report.ShapeInterpretation]
                ]);
        }

        private ExportSheet BuildPercentileSheet()
        {
            return new(
                Resource.RptPercentileTable,
                [Resource.RptPercentile, Resource.Score, Resource.RptMeaning],
                _report!.Percentiles.Select(x => (IEnumerable<object?>)[x.Label, x.Score, x.Meaning])
            );
        }

        private ExportSheet BuildBandSheet()
        {
            return new(
                Resource.RptScoreBandBreakdown,
                [Resource.RptBand, Resource.RptCount, "%", Resource.RptCutScore],
                _report!.Bands.Select(x => (IEnumerable<object?>)[x.Band, x.Count, x.Percentage, x.ContainsCutScore ? Resource.Yes : Resource.No]));
        }

        private void ResetReport()
        {
            _report = null;

            _errorMessage = null;

            _noDataMessage = null;

            _histogramSvgCache = null;
        }

        private record YAxisTick(double Y, string Label);

        private record StatCard(string Label, string Value, string ValueStyle = "", string SubText = "");
    }
}

